name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: libraries/js/package-lock.json

      - name: Install dependencies
        working-directory: libraries/js
        run: npm ci

      - name: Lint
        working-directory: libraries/js
        run: npm run lint:ci

      - name: Unit Test
        working-directory: libraries/js
        run: npm run test

      - name: Build
        working-directory: libraries/js
        run: npm run build

      - name: Package dry run
        working-directory: libraries/js/dist
        run: npm pack
