name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm" # Enabling npm caching
          cache-dependency-path: |
            libraries/js/package-lock.json
            tools/siwa-mock/package-lock.json
            tools/js-example/package-lock.json

      - name: Install dependencies
        working-directory: libraries/js
        run: npm ci

      - name: Lint
        working-directory: libraries/js
        run: npm run lint:ci

      - name: Unit Test
        working-directory: libraries/js
        run: npm run test

      - name: Build
        working-directory: libraries/js
        run: npm run build

      - name: Package dry run
        working-directory: libraries/js/dist
        run: npm pack

      # Start up the mock server
      - name: Mock server install
        working-directory: tools/siwa-mock
        run: npm ci

      - name: Start mock server
        working-directory: tools/siwa-mock
        run: |
          npm run start &
          sleep 1

      # Run the example tests
      - name: JS-Example install
        working-directory: tools/js-example
        run: npm i ../../libraries/js/dist/projectlibertylabs-siwa-0.0.0.tgz

      - name: Run the example tests
        working-directory: tools/js-example
        run: npm test

  generator-tool:
    strategy:
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.36.2-jammy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm" # Enabling npm caching
          cache-dependency-path: |
            libraries/js/package-lock.json
            tools/signed-request-generator/package-lock.json

      - name: Install Library dependencies
        working-directory: libraries/js
        run: npm ci

      - name: Build Library
        working-directory: libraries/js
        run: npm run build

      - name: Package Library
        working-directory: libraries/js/dist
        run: npm pack

      - name: Install dependencies
        working-directory: tools/signed-request-generator
        run: npm i ../../libraries/js/dist/projectlibertylabs-siwa-0.0.0.tgz

      - name: Lint
        working-directory: tools/signed-request-generator
        run: npm run lint

      - name: Unit Test
        working-directory: tools/signed-request-generator
        run: npm run test

      - name: Build
        working-directory: tools/signed-request-generator
        run: npm run build

      - name: Install Playwright Browsers
        working-directory: tools/signed-request-generator
        run: npx playwright install chromium # does not need "--with-deps" because we are using the official image

      - name: Run the tests
        working-directory: tools/signed-request-generator
        run: npm test
