# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - docs/**
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build mdbook
  build-mdbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up mdBook 📚
        uses: ./.github/workflows/common/set-up-mdbook
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Generator Tool - Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm" # Enabling npm caching
          cache-dependency-path: |
            libraries/js/package-lock.json
            tools/signed-request-generator/package-lock.json

      - name: Generator Tool - Install Library dependencies
        working-directory: libraries/js
        run: npm ci

      - name: Generator Tool - Build Library
        working-directory: libraries/js
        run: npm run build

      - name: Generator Tool - Package Library
        working-directory: libraries/js/dist
        run: npm pack

      - name: Generator Tool - Install dependencies
        working-directory: tools/signed-request-generator
        run: npm i ../../libraries/js/dist/projectlibertylabs-siwa-0.0.0.tgz

      - name: Generator Tool - Build
        working-directory: tools/signed-request-generator
        run: npm run build

      - name: Generator Tool - Copy Build
        run: cp -a tools/signed-request-generator/build docs/src/Generator

      - name: Build with mdBook
        working-directory: docs
        run: mdbook build && ls book

      # Upload the mdBook output to GitHub Pages
      - name: Upload mdbook to GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          name: mdbook
          path: ./docs/book

  # Deployment job
  deploy:
    name: Deploy mdbook to GitHub Pages
    runs-on: ubuntu-latest
    needs: [build-mdbook]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download mdbook artifact
        uses: actions/download-artifact@v4
        with:
          name: mdbook
          path: ./docs

      - name: Upload final result to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
